server:
  port: 18080
spring:
  application:
    name: docker-workshop-backend
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://workshop-db:3306/workshop
    username: root
    password: 1q2w3e4r
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: localhost
    port: 6379
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1
    password: go-to-the-moon